const LANGUAGE_DISPLAY_NAMES: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  jsx: 'JSX',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  tsx: 'TSX',
  html: 'HTML',
  markup: 'HTML',
  xml: 'XML',
  css: 'CSS',
  scss: 'SCSS',
  json: 'JSON',
  yaml: 'YAML',
  yml: 'YAML',
  toml: 'TOML',
  graphql: 'GraphQL',
  regex: 'Regex',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  cs: 'C#',
  rust: 'Rust',
  go: 'Go',
  java: 'Java',
  swift: 'Swift',
  kotlin: 'Kotlin',
  python: 'Python',
  py: 'Python',
  ruby: 'Ruby',
  rb: 'Ruby',
  bash: 'Bash',
  shell: 'Shell',
  sh: 'Shell',
  powershell: 'PowerShell',
  ps1: 'PowerShell',
  perl: 'Perl',
  php: 'PHP',
  batch: 'Batch',
  bat: 'Batch',
  autohotkey: 'AutoHotkey',
  ahk: 'AutoHotkey',
  vbnet: 'VB.NET',
  vba: 'VBA',
  'visual-basic': 'VB',
  cshtml: 'Razor C#',
  razor: 'Razor C#',
  sql: 'SQL',
  mongodb: 'MongoDB',
  markdown: 'Markdown',
  md: 'Markdown',
  diff: 'Diff',
  docker: 'Docker',
  dockerfile: 'Dockerfile',
  git: 'Git',
  ignore: '.ignore',
  gitignore: '.gitignore',
  apacheconf: 'Apache Conf',
  apex: 'Apex',
  arduino: 'Arduino',
  smalltalk: 'Smalltalk',
};

export function getLanguageDisplayName(lang: string): string {
  return LANGUAGE_DISPLAY_NAMES[lang] ?? lang;
}
